import type { DemoEvent, LiveState } from "@/lib/types";

// Keep the server/client fallback identical during hydration. Live values replace it after connection.
const now = new Date("2026-08-22T00:00:00.000Z");
const isoMinutesAgo = (minutes: number) => new Date(now.getTime() - minutes * 60_000).toISOString();
const retained = (date: string) => {
  const value = new Date(date);
  value.setUTCFullYear(value.getUTCFullYear() + 1);
  return value.toISOString();
};

export const seedEvents: DemoEvent[] = [
  {
    id: "evt-demo-ppe",
    deviceId: "CAM-01",
    trackId: 7,
    occurredAt: isoMinutesAgo(2),
    type: "ppe_violation",
    title: "Gloves not detected",
    detail: "A tracked person remained in Preparation without complete hand protection for 3 seconds.",
    severity: "critical",
    sourceMode: "simulated",
    status: "new",
    employeeId: "EMP-001",
    employeeName: "Demo Operator A",
    zone: "Preparation",
    confidence: 0.92,
    evidenceUrl: null,
    retentionUntil: retained(isoMinutesAgo(2)),
  },
  {
    id: "evt-demo-process",
    deviceId: "CAM-01",
    trackId: 7,
    occurredAt: isoMinutesAgo(4),
    type: "process_started",
    title: "Chicken Washing started",
    detail: "Tagged tray TRAY-01 entered the configured process start area.",
    severity: "info",
    sourceMode: "simulated",
    status: "acknowledged",
    employeeId: "EMP-001",
    employeeName: "Demo Operator A",
    zone: "Preparation",
    confidence: 0.97,
    evidenceUrl: null,
    retentionUntil: retained(isoMinutesAgo(4)),
  },
  {
    id: "evt-demo-temp",
    deviceId: "CAM-01",
    trackId: null,
    occurredAt: isoMinutesAgo(11),
    type: "temperature_alert",
    title: "Temperature exceeded demo limit",
    detail: "Simulated Cold Storage Demo reading reached 8.1°C.",
    severity: "warning",
    sourceMode: "simulated",
    status: "dismissed",
    employeeId: null,
    employeeName: null,
    zone: "Cold Storage Demo",
    confidence: 1,
    evidenceUrl: null,
    retentionUntil: retained(isoMinutesAgo(11)),
  },
];

export const fallbackState: LiveState = {
  health: {
    edge: "offline",
    camera: "offline",
    cloud: "degraded",
    livekit: "offline",
    stream: "offline",
    sensor: "online",
    storage: "offline",
    storageError: "Local edge service is not connected.",
    cameraId: "facetime",
    cameraLabel: "FaceTime HD Camera",
    cameraSwitchState: "idle",
    cameraSwitchMessage: null,
    sourceType: "avfoundation",
    modelLabel: "Controlled demo pipeline",
    processedFps: 0,
    automaticMonitoring: "unavailable",
    monitoringMessage: "Automatic monitoring is unavailable until the local edge service starts.",
    queueDepth: 0,
    lastFrameAt: null,
    updatedAt: now.toISOString(),
  },
  activeEmployee: null,
  detection: {
    status: "idle",
    trackId: null,
    identityDetected: false,
    identityStatus: {
      state: "not_associated",
      label: "Identity not associated",
      detail: "PPE monitoring does not require employee identity.",
    },
    ppeDetected: false,
    issues: [],
    ppeItems: {},
    readiness: null,
    proof: null,
    resetGeneration: 0,
    lastResetAt: null,
    updatedAt: null,
  },
  process: {
    id: null,
    label: "Chicken Washing",
    status: "idle",
    startedAt: null,
    elapsedSeconds: 0,
    targetMinSeconds: 120,
    targetMaxSeconds: 180,
  },
  temperature: {
    sensorId: "TEMP-SIM-01",
    label: "Cold Storage Demo",
    valueC: 4.2,
    minC: 0,
    maxC: 5,
    status: "safe",
    sourceMode: "simulated",
    sampledAt: now.toISOString(),
  },
  inventory: [
    { sku: "SKU-001", label: "Product A", quantity: 5, unit: "items" },
    { sku: "SKU-002", label: "Product B", quantity: 8, unit: "items" },
    { sku: "SKU-003", label: "Product C", quantity: 3, unit: "items" },
    { sku: "SKU-004", label: "Product D", quantity: 6, unit: "items" },
    { sku: "SKU-005", label: "Product E", quantity: 4, unit: "items" },
  ],
  recentEvents: seedEvents,
};
