"use client";

import { useState } from "react";
import { BellRing, Camera, CheckCircle2, Cloud, Database, FileClock, HardDrive, KeyRound, PlugZap, RotateCcw, Server, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { DataBoundary, SourceBadge } from "@/components/enterprise-shared";
import { PageHeader } from "@/components/page-header";
import { ConnectionBadge, StatusBadge } from "@/components/status-badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Separator } from "@/components/ui/separator";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useEnterprise } from "@/hooks/use-enterprise";
import { useEdgeState } from "@/hooks/use-edge";
import { formatDateTime } from "@/lib/format";

interface AuditRecord { id: string; entityType: string; entityId: string; actor: string; action: string; detail: Record<string, unknown>; createdAt: string }

export function PlatformView() {
  const { context, oracle, resetSimulated } = useEnterprise();
  const { state } = useEdgeState();
  const [confirmation, setConfirmation] = useState("");
  const [audit, setAudit] = useState<AuditRecord[]>([]);
  const [auditLoaded, setAuditLoaded] = useState(false);
  const services = [
    { name: "Camera source", icon: Camera, state: state.health.camera, detail: `${state.health.cameraLabel} · ${state.health.sourceType}`, recovery: "Verify camera permission and source URL." },
    { name: "Edge AI service", icon: Server, state: state.health.edge, detail: `${state.health.processedFps.toFixed(1)} processed fps`, recovery: "Restart the local edge agent." },
    { name: "PPE decision verifier", icon: ShieldCheck, state: state.health.ppeVerifier?.status === "passed" ? "online" as const : "offline" as const, detail: state.health.ppeVerifier?.status === "passed" ? "Automatic startup self-test passed" : state.health.ppeVerifier?.failures.join(" · ") || "Verifier self-test has not passed", recovery: "Do not present live PPE; use the labelled fallback and review the verifier." },
    { name: "Local evidence store", icon: HardDrive, state: state.health.storage, detail: state.health.storage === "online" ? `${state.health.queueDepth} queued records · write self-test passed` : state.health.storageError ?? "Storage self-test failed", recovery: "Check the writable data and evidence directories before continuing." },
    { name: "Cloud synchronization", icon: Cloud, state: state.health.cloud, detail: state.health.cloud === "online" ? "Configured" : "Optional in local mode", recovery: "Add valid client cloud credentials when required." },
    { name: "Live video transport", icon: PlugZap, state: state.health.livekit, detail: state.health.livekit === "online" ? "Connected" : "Local video fallback active", recovery: "Add managed-streaming credentials when required." },
    { name: "Temperature adapter", icon: Database, state: state.health.sensor, detail: state.health.temperatureSource?.sourceMode === "real" ? `${state.health.temperatureSource.kind.toUpperCase()} physical source` : "Software simulator · Simulated", recovery: "Select and calibrate a serial or network sensor for production." },
  ];

  async function loadAudit() {
    if (auditLoaded) return;
    try { const response = await fetch("/api/edge/api/enterprise/audit-log", { cache: "no-store" }); const payload = await response.json() as { items: AuditRecord[] }; setAudit(payload.items); setAuditLoaded(true); }
    catch { toast.error("Audit log could not be loaded."); }
  }

  async function reset() {
    try { const removed = await resetSimulated(); setConfirmation(""); toast.success(`Reset complete: ${removed.events} simulated events and ${removed.incidents} simulated incidents removed.`); }
    catch (reason) { toast.error(reason instanceof Error ? reason.message : "Reset failed."); }
  }

  return <div className="page-shell enterprise-page platform-page">
    <PageHeader eyebrow="IT administration · Demo view" title="Platform" description="Inspect service health, alert readiness, integration boundaries, retention controls, and auditable operator actions." actions={<StatusBadge tone={state.health.edge === "online" && state.health.storage === "online" && state.health.ppeVerifier?.status === "passed" ? "safe" : "warning"} label={state.health.edge === "online" && state.health.storage === "online" && state.health.ppeVerifier?.status === "passed" ? "Core local services ready" : "Readiness needs attention"} />} />
    <Tabs defaultValue="fleet" onValueChange={(value) => { if (value === "audit") void loadAudit(); }}>
      <TabsList className="platform-tabs" variant="line"><TabsTrigger value="fleet">Fleet & health</TabsTrigger><TabsTrigger value="alerts">Alerts</TabsTrigger><TabsTrigger value="oracle">Oracle readiness</TabsTrigger><TabsTrigger value="audit">Audit log</TabsTrigger><TabsTrigger value="controls">Demo controls</TabsTrigger></TabsList>
      <TabsContent value="fleet"><section className="panel health-matrix enterprise-health"><div className="enterprise-panel-heading"><div><span className="eyebrow">Service matrix</span><h2>Component health and recovery</h2><p>Named vendors are omitted from the operating matrix; configuration details remain internally testable.</p></div></div><Separator /><Table><TableHeader><TableRow><TableHead>Component</TableHead><TableHead>Status</TableHead><TableHead>Operational detail</TableHead><TableHead>Recovery guidance</TableHead></TableRow></TableHeader><TableBody>{services.map(({ name, icon: Icon, state: serviceState, detail, recovery }) => <TableRow key={name}><TableCell><span className="service-name"><i><Icon /></i><strong>{name}</strong></span></TableCell><TableCell><ConnectionBadge state={serviceState} /></TableCell><TableCell className="service-detail">{detail}</TableCell><TableCell className="recovery-copy">{recovery}</TableCell></TableRow>)}</TableBody></Table></section><section className="platform-context-grid"><article className="panel platform-config"><div className="enterprise-panel-heading"><div><span className="eyebrow">Enterprise context</span><h2>Configured scope</h2></div></div><dl><div><dt>Facilities</dt><dd>{context.sites.length}</dd></div><div><dt>Operational workspaces</dt><dd>{context.workspaces.filter((item) => item.mode !== "planned").length}</dd></div><div><dt>Timezone</dt><dd>Asia/Kuwait</dd></div><div><dt>Retention policy</dt><dd>Minimum 365 days</dd></div><div><dt>Camera audio</dt><dd>Disabled</dd></div><div><dt>Facial recognition</dt><dd>Disabled</dd></div></dl></article><article className="panel platform-config"><div className="enterprise-panel-heading"><div><span className="eyebrow">Security boundary</span><h2>Local demo controls</h2></div><ShieldCheck /></div><p>Secrets remain in ignored environment files. Device and user credentials are separated. Production authorization and client identity controls require deployment design and client approval.</p><DataBoundary mode="live">Local camera, events, evidence, reports, and demo tools operate without cloud credentials.</DataBoundary></article></section></TabsContent>
      <TabsContent value="alerts"><section className="panel alert-rules-panel"><div className="enterprise-panel-heading"><div><span className="eyebrow">Escalation readiness</span><h2>Alert channels and rules</h2><p>Browser alerts are demonstrable. External channels are visible but intentionally not represented as configured.</p></div></div><Separator />{[{ name: "PPE critical violation", event: "ppe_violation", browser: true }, { name: "Temperature excursion", event: "temperature_alert", browser: true }, { name: "Process timing exception", event: "process_exception", browser: false }].map((rule) => <article key={rule.event}><span><BellRing /></span><div><strong>{rule.name}</strong><small className="mono">{rule.event}</small></div><StatusBadge tone={rule.browser ? "safe" : "neutral"} label={rule.browser ? "Browser enabled" : "Browser off"} /><StatusBadge tone="warning" label="Email not configured" /><StatusBadge tone="warning" label="SMS not configured" /></article>)}</section></TabsContent>
      <TabsContent value="oracle"><section className="oracle-layout"><article className="panel oracle-readiness"><div className="oracle-status-mark"><PlugZap /></div><span className="eyebrow">ERP integration boundary</span><h2>Oracle ERP is not connected</h2><p>{oracle?.message ?? "Client Oracle product, version, APIs, and credentials are required before connection."}</p><div className="oracle-guard"><KeyRound /><span><strong>No external requests are enabled</strong>Sample payloads and mappings are presentation-only.</span></div></article><article className="panel enterprise-table-panel"><div className="enterprise-panel-heading"><div><span className="eyebrow">Proposed contract</span><h2>Integration mappings</h2><p>Final objects and APIs depend on the client’s Oracle product and version.</p></div><SourceBadge mode="simulated" /></div><Table><TableHeader><TableRow><TableHead>ORVIA source</TableHead><TableHead>Proposed Oracle target</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{oracle?.mappings.map((mapping) => <TableRow key={mapping.source}><TableCell className="mono">{mapping.source}</TableCell><TableCell>{mapping.target}</TableCell><TableCell><StatusBadge tone="warning" label="Proposed" /></TableCell></TableRow>)}</TableBody></Table></article></section></TabsContent>
      <TabsContent value="audit"><section className="panel enterprise-table-panel audit-panel"><div className="enterprise-panel-heading"><div><span className="eyebrow">Immutable operator history</span><h2>Audit log</h2><p>Incident changes and notes are recorded with actor, action, entity, and timestamp.</p></div><FileClock /></div><Table><TableHeader><TableRow><TableHead>Actor</TableHead><TableHead>Action</TableHead><TableHead>Entity</TableHead><TableHead>Timestamp</TableHead></TableRow></TableHeader><TableBody>{audit.length ? audit.map((record) => <TableRow key={record.id}><TableCell>{record.actor}</TableCell><TableCell>{record.action}</TableCell><TableCell><strong>{record.entityType}</strong><small className="mono">{record.entityId.slice(0, 12)}</small></TableCell><TableCell><time className="mono" dateTime={record.createdAt}>{formatDateTime(record.createdAt)}</time></TableCell></TableRow>) : <TableRow><TableCell colSpan={4}><div className="enterprise-empty"><FileClock /><strong>{auditLoaded ? "No audit actions recorded" : "Loading audit log"}</strong><span>Incident updates and operator notes will appear here.</span></div></TableCell></TableRow>}</TableBody></Table></section></TabsContent>
      <TabsContent value="controls"><section className="platform-controls-grid"><article className="panel platform-danger-zone"><span><RotateCcw /></span><div><span className="eyebrow">Controlled reset</span><h2>Reset simulated presentation data</h2><p>Removes only records explicitly marked Simulated and restores tagged demonstration inventory. Real-source records are preserved.</p></div><Dialog><DialogTrigger asChild><Button variant="destructive">Reset simulated data</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Reset simulated presentation data?</DialogTitle><DialogDescription>This removes simulated events, incidents, process runs, sensor records, and inventory transactions. It does not delete real-source records.</DialogDescription></DialogHeader><label className="confirmation-field">Type <strong>RESET SIMULATED DATA</strong><Input value={confirmation} onChange={(event) => setConfirmation(event.target.value)} /></label><DialogFooter><DialogClose asChild><Button variant="outline">Cancel</Button></DialogClose><Button variant="destructive" disabled={confirmation !== "RESET SIMULATED DATA"} onClick={() => void reset()}>Confirm reset</Button></DialogFooter></DialogContent></Dialog></article><article className="panel platform-config"><div className="enterprise-panel-heading"><div><span className="eyebrow">Safety guarantees</span><h2>Reset boundary</h2></div><CheckCircle2 /></div><ul><li>Requires an exact typed confirmation.</li><li>Targets source_mode = simulated only.</li><li>Preserves real camera-origin records.</li><li>Restores only the five controlled demo SKUs.</li></ul></article></section></TabsContent>
    </Tabs>
  </div>;
}
